### ISSUE TITLE
Smoke tests do not properly fail with TLS enabled

### ISSUE THREAD

**Issue by mxplusb** [minio/minio-boshrelease#135]
With this deployment configuration
```yaml
- azs:
  - z1
  instances: 1
  jobs:
  - name: minio-server
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 443
      server_cert: ((minio-tls.certificate))
      server_key: ((minio-tls.private_key))
    provides:
      minio-server:
        as: minio-link
    release: minio
  name: minio
  networks:
  - name: default
    static_ips:
    - x.x.x.x
  persistent_disk_type: 100GB
  stemcell: default
  vm_type: small
- azs:
  - z1
  instances: 1
  jobs:
  - consumes:
      minio:
        from: minio-link
    name: smoke-tests
    release: minio
    templates:
    - name: smoke-tests
  lifecycle: errand
  name: tests
  networks:
  - name: default
  persistent_disk_type: 10GB
  post_deploy: true
  stemcell: default
  vm_type: small
```
The smoke tests give a false positive result, failing even when the bosh errand succeeds.
```
Using deployment 'minio'

Task 2121

Task 2121 | 22:16:46 | Preparing deployment: Preparing deployment
Task 2121 | 22:16:49 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2121 | 22:16:49 | Preparing deployment: Preparing deployment (00:00:03)
Task 2121 | 22:16:49 | Creating missing vms: tests/64144857-322d-4df4-b6f7-75d7beab1f7c (0) (00:02:37)
Task 2121 | 22:19:27 | Updating instance tests: tests/64144857-322d-4df4-b6f7-75d7beab1f7c (0) (canary) (00:00:26)
Task 2121 | 22:19:53 | Running errand: tests/64144857-322d-4df4-b6f7-75d7beab1f7c (0) (00:00:01)
Task 2121 | 22:19:54 | Fetching logs for tests/64144857-322d-4df4-b6f7-75d7beab1f7c (0): Finding and packing log files (00:00:01)

Task 2121 Started  Thu Feb 13 22:16:46 UTC 2020
Task 2121 Finished Thu Feb 13 22:19:55 UTC 2020
Task 2121 Duration 00:03:09
Task 2121 done

Instance   tests/64144857-322d-4df4-b6f7-75d7beab1f7c  
Exit Code  0  
Stdout     -  
Stderr     mc: <ERROR> Unable to make bucket `myminio/test`. 400 Bad Request  
```
