### ISSUE TITLE
How to run distributed MinIO with TLS enabled?

### ISSUE THREAD

**Issue by mchudinov** [minio/minio-boshrelease#151]
How to run distributed MinIO with TLS enabled using self signed certificates generated by Bosh ?
I have 4 MinIO instances deployed using Bosh release. Instances can not connect to each other because of certificate issue.
This is error log from one of the instances:
```
Unable to read 'format.json' from https://10.39.148.82:9000/var/vcap/store/minio-server: Post "https://10.39.148.82:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: cannot validate certificate for 10.39.148.82 because it doesn't contain any IP SANs
Unable to read 'format.json' from https://10.39.148.83:9000/var/vcap/store/minio-server: Post "https://10.39.148.83:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: cannot validate certificate for 10.39.148.83 because it doesn't contain any IP SANs
Unable to read 'format.json' from https://10.39.148.85:9000/var/vcap/store/minio-server: Post "https://10.39.148.85:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: cannot validate certificate for 10.39.148.85 because it doesn't contain any IP SANs
```

**Comment by klauspost** [comment]
MinIO does not provide any Bosh setup. We cannot provide support for that, even if your post included the relevant information.

Feel free to ask the community for help [on slack](https://slack.min.io/) or check if the Bosh community can help you.

**Comment by mchudinov** [comment]
After searching the internet for a couple of hours I have found that **dns_alias** option can help.
When the **dns_alias** option is set, the following new errors come out:
```
Unable to read 'format.json' from https://xxx1.minio.net.minio.bosh:9000/var/vcap/store/minio-server: Post "https://xxx1.minio.net.minio.bosh:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Unable to read 'format.json' from https://xxx2.minio.net.minio.bosh:9000/var/vcap/store/minio-server: Post "https://xxx2.minio.net.minio.bosh:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Unable to read 'format.json' from https://xxx3.minio.net.minio.bosh:9000/var/vcap/store/minio-server: Post "https://xxx3.minio.net.minio.bosh:9000/minio/storage/var/vcap/store/minio-server/v20/readall?disk-id=&file-path=format.json&volume=.minio.sys": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
How to solve this?

Here is how I generate certificates for MinIO with Bosh:
```
variables:
  - name: minio_ca
    type: certificate
    options:
      is_ca: true
      common_name: "MinIO Certificate Authority"
  - name: minio_certificate
    type: certificate
    options:
      ca: minio_ca
      common_name: "*.minio.mgmt-net.minio.bosh"
      alternative_names: ["*.minio.net.minio.bosh"]
      extended_key_usage: ["client_auth","server_auth"]      
```

The **minio_certificate** certificate should be generated with SAN as soon as **alternative_names** option is in use in Bosh. 
What is wrong?
