### ISSUE TITLE
Error after increasing number of nodes in a distrbuted MinIO Bosh deployment

### ISSUE THREAD

**Issue by mchudinov** [minio/minio-boshrelease#161]
There is a distributed Bosh MinIO deployment quite similar to what is defined in this repository example `manifest-dist-example.yml`.

After the number of nodes is increased from 4 to 6 and redeployment the first MinIO (node number 0) is in `failing` state.

The following error message is shown in   `/var/vcap/sys/log/minio-server/minio-server.stdout.log`:

```
Error: https://xxx.minio.net.s3.bosh:9000/var/vcap/store/minio-server as has incorrect configuration: 
Expected number of endpoints 6, seen 4
       1: cmd/server-main.go:471:cmd.serverMain()
```

The following update strategy is defined in manifest (same as in example file `manifest-dist-example.yml`):
```
update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1
```

I have tried this update strategy with the same error result:
```
update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1
  vm_strategy: delete-create
```
How to increase the number of nodes in a distributed MinIO cluster with Bosh?

**Comment by mchudinov** [comment]
Updates do not work either with `create-swap-delete` strategy. Same error with and without `serial: true`

The existing MinIO node 0 comes to a failing state while two new VMs are not yet started. 

The screenshot shows a cluster after update from 4 to 6 nodes using the following update strategy:

```YAML
update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1
  vm_strategy: create-swap-delete 
  serial: true
```
![Bosh-20210426-142219](https://user-images.githubusercontent.com/2603415/116099949-c1be6c00-a6ac-11eb-9cff-9d081382e294.png)
